- name: configure user
  hosts: user
  become: yes
  tasks:
    - name: pign the user server
      ansible.builtin.ping:
      
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable  nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y
      
    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add create the system user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: Recursively delete and remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Recursively delete and remove user zip file in tmp/user.zip
      ansible.builtin.file:
        path: /tmp/user.zip
        state: absent
        
    - name: Downloading the user zip file in tmp/catalogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
        dest: /tmp/user.zip
 
    - name: unzipping & unarchive the user in /app from /tmp/catalogue.zip
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app  
        remote_src: yes

    - name: adding npm dependencies to package.nodejs that in /app directory
      community.general.npm:
        path: /app

    - name: Copy user systemctl service
      ansible.builtin.template:
        src: user.service
        dest: /etc/systemd/system/user.service
      
    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start or restarted user
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes


   

   
       
