[local]
localhost

[mongodb]
mongodb-dev.devsecopsaws88s.online

[redis]
redis-dev.devsecopsaws88s.online

[mysql]
mysql-dev.devsecopsaws88s.online

[rabbitmq]
rabbitmq-dev.devsecopsaws88s.online

[catalogue]
catalogue-dev.devsecopsaws88s.online

[user]
user-dev.devsecopsaws88s.online

[cart]
cart-dev.devsecopsaws88s.online

[shipping]
shipping-dev.devsecopsaws88s.online

[payment]
payment-dev.devsecopsaws88s.online



[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321


CATALOGUE_HOST=catalogue-dev.devsecopsaws88s.online
USER_HOST=user-dev.devsecopsaws88s.online
CART_HOST=cart-dev.devsecopsaws88s.online
SHIPPING_HOST=shipping-dev.devsecopsaws88s.online
PAYMENT_HOST=payment-dev.devsecopsaws88s.online


MONGODB_HOST=mongodb-dev.devsecopsaws88s.online
REDIS_HOST=redis-dev.devsecopsaws88s.online
MYSQL_HOST=mysql-dev.devsecopsaws88s.online
RABBITMQ_HOST=rabbitmq-dev.devsecopsaws88s.online


