- name: route53 records
  hosts: all
  connection: local

  vars:
    instances_env: dev
    domain_name: devsecopsaws88s.online
    action: create

  tasks:
    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
      register: ec2_instances_output
      when: action == "create"

    - name: create rout53 records 
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ instances_env }}.{{ domain_name }}" # mongodb-dev.devsecopsaws88s.online, catalogue-dev.devsecopsaws88s.online
        type: A
        ttl: 1
        value: "{{item.instances[0].private_ip_address}}" # List
        wait: true
      loop: "{{ ec2_instances_output.results }}"
      when: action == "create"

    - name: create rout53 records for frontend
      amazon.aws.route53:
          state: present
          zone: "{{ domain_name }}"
          record: "roboshop-{{ instances_env }}.{{ domain_name }}" # roboshop-dev.devsecopsaws88s.online
          type: A
          ttl: 1
          value: "{{item.instances[0].public_ip_address}}"
          wait: true
      loop: "{{ ec2_instances_output.results }}"
      when: 
        - item.item == "frontend"
        - action == "create"


    - name: delete aws route 53 records
      amazon.aws.route53:
        state: absent     
        record: "{{ item }}-{{ instances_env }}.{{ domain_name }}" # roboshop-dev.devsecopsaws88s.online, frontend-dev.devsecopsaws88s.online
        type: A
        ttl: 1
      loop: "{{ ec2_intances_names }}"
      when: action=="destroy"


 