- name: route53 records
  hosts: all
  connection: local

  vars:
    instances_env: dev
    domain_name: devsecopsaws88s.online
    action: create

  tasks:
    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
      register: ec2_instances_output
      when: action == "create"

    - name: printing the information of all instances
      ansible.builtin.debug:
         msg: ec2_instance_output

    

 