- name: configure mysql
  hosts: mysql
  become: yes
  tasks:
    - name: install MYSQL server
      ansible.builtin.dnf:
       name: mysql-server
       status: present

    - name: enable and start or restarted the mysql service
      ansible.builtin.service:
       name: mysqld
       status: restartedstarted
       enabled: yes

    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
      
