- name: configure mysql
  hosts: mysql
  become: yes
  tasks:
    - name: Install MYSQL server
      ansible.builtin.dnf:
       name: mysql-server
       status: present

    - name: start and enable or restarted the mysql service
      ansible.builtin.service:
       name: mysqld
       status: restartedstarted
       enabled: yes

    - name: Setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
      
