- name: configure rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks: 
    - name: Copy rabbitmq repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: Install RabbitMQ
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: start and enable the rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        status: restarted
        enable: yes

    - name: Start RabbitMQ
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: started
        enabled: yes


    - name: Check services
      ansible.builtin.shell: systemctl list-units --type=service | grep rabbitmq
      register: rabbitmq_services


    - name: printing the rabbitmq services
      debug:
        var: rabbitmq_services.stdout


    - name: The user doesn't have topic permission rules for other vhosts
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
        state: present
          