- name: print user nama and password using prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: "please enter username:"
    private: false

  - name: password
    prompt: "please enter password"
    private: true
  
  tasks:
  - name: print the username and password
    ansible.builtin.debug:
      msg: "username is: {{ username }} , password is: {{ password }}"
  
      


   