- name: playbook or play level variables
  hosts: local
  connection: local
  tasks:
  - name: printing the variables
    ansible.builtin.debug:
     msg: "course is: {{ COURSE }},The Triner is: {{ TRAINER }},The Duration is: {{ DURATION }}" 