- name: check the number less then 10
  hosts: local
  connection: local
  vars:
   NUMBEROFSESSIONS: 10
  tasks:
  - name: Checking the sessions
    ansible.builtin.debug:
     msg: "Yes Your Attendence The Sessions And Your Is Marked"
    when: NUMBEROFSESSIONS >=10
