- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
    - name: enable nginx 1.24
      ansible.builtin.shell: dnf module enable nginx:1.24 -y

    - name: install nginx
      ansible.buitin.dnf:
        name: nginx
        status: present

    - name: Remove And Delete the file completely
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Recreate an empty file
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Downloading the frontend zip file in tmp/frontend.zip
      ansible.builtin.get_url:
        url: /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
        dest: /tmp/frontend.zip
 
    - name: unzipping & unarchive the frontend in /app from /tmp/frontend.zip
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html 
        remote_src: yes


    - name: Copy nginx.conf
      ansible.builtin.template:
      src: frontend.service
      dest: /etc/nginx/nginx.conf

    
    - name: start or restarted shipping
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes