- name: ansible command module vs shell module
  hosts: local
  connection: local
  tasks:
    - name: ansible command module vs shell module test for user
      # ansible.builtin.command  cat /etc/passwd | grep root ---> not works here
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: users_output

    - name: print users output
      ansible.builtin.debug:
        msg: "{{ users_output }}"
    
    - name: ansible command module vs shell module test for files
      # ansible.builtin.command not works here
      ansible.builtin.shell: ls -ltr > files.txt
      register: files_output
  
    - name: print files output
      ansible.builtin.debug:
        msg: "{{ files_output }}"

    - name: print output
      debug:
        var: users_output.stdout

    - name: checking the user is exsiting in the server roboshop user id
      ansible.builtin.command: id roboshop 
      register: user_output
      ignore_errors: true

    - name: print the user_output
      ansible.builtin.debug:
      msg: "{{ user_output }}"
    
    - name: create user
      ansible.builtin.command: useradd roboshop
      when: user_output.rc != 0
        