- name: creating ec2 intances And rout53 records
  hosts: all
  connection: local
  vars:
    sgid: sg-0cc36aed8dd6406ca
    amiid: ami-0220d79f3f480ecf5
    instancesenv: dev
    myec2intances: 
      - mongodb
      - catalogue
  tasks:
    - name: creating ec2 intances
      amazon.aws.ec2_instance:
       instance_ids: t3.micro
       securitygroupid: "{{ sgid }}"
       ami_id: "{{ amiid }}"
       name: "{{ item }}"
       tags: 
        Project: roboshop
        Component: "{{ item }}"
        Enviroment: "{{ instancesenv }}"
        name: "{{ item }}-{{ instancesenv }}"
      loop: "{{ myec2intances }}"
      register: ec2_instance


    - name: ec2_instance_output
      ansible.builtin.debug:
        msg: "{{ ec2_instance }}"

