- name: enable  nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y
  
- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present


- name: adding npm dependencies to package.nodejs that in /app directory
  community.general.npm:
    path: /app